
[[weeks]]
num = 1

[[weeks.days]]
date = "Jan 9"
topic = "Class Introduction; High-Quality Software"
reading = ""
assignment = "Sprint 0 Start"

[[weeks.days]]
date = "Jan 11"
topic = "High-Quality Software; C# and Object-Oriented Programming"
reading = "(Reference) C# in a Nutshell"
assignment = "Sprint 0"

[[weeks.days]]
date = "Jan 13"
topic = "Visual Studio; MonoGame; User Input Handling"
reading = "(Reference) C# in a Nutshell; (Required) Head-First Design Patterns Ch. 1"
assignment = "Sprint 0"

[[weeks]]
num = 2

[[weeks.days]]
date = "Jan 16"
topic = "No Class"
assignment = "Sprint 0"

[[weeks.days]]
date = "Jan 18"
topic = "2D Coordinate Systems; Textures and Sprites"
reading = "MonoGame Tutorials (start <a target=\"_blank\" href=\"http://rbwhitaker.wikidot.com/monogame-2d-tutorials\">here</a>)"
assignment = "Sprint 0"

[[weeks.days]]
date = "Jan 20"
topic = "Sprint 0 Design Comparisons"
reading = "Head-First Design Patterns (Ch 1); or Gang of Four (Ch 1)"
assignment = "Sprint 0 Early Deadline on Sun Jan 22 at 11:59pm"

[[weeks]]
num = 3

[[weeks.days]]
date = "Jan 23"
topic = "Command Pattern; Agile Development"
reading = "Head First Design Patterns (Ch 6); or Gang of Four (Ch 19)"
assignment = "Sprints 0 And 1"

[[weeks.days]]
date = "Jan 25"
topic = "Version Control; Git and GitHub"
assignment = "Sprints 0 And 1"

[[weeks.days]]
date = "Jan 27"
topic = "Group Project Aspirations; Requirements Gathering; Texture2D Encapsulation"
assignment = "Sprint 0 Due on Sun Jan 29 at 11:59pm; Sprint 1 Wrap-Up; Sprint 2 Start"

[[weeks]]
num = 4

[[weeks.days]]
date = "Jan 30"
topic = "State Machine; State Design Pattern; Separation of Sprites from Game Objects"
reading = "Head-First Design Patterns (Ch 10); or  Gang of Four (Ch 20)"
assignment = "Sprint 2"

[[weeks.days]]
date = "Feb 1"
topic = "Decorator Pattern; Interaction Between Decorators and States; Link Decorator for Zelda"
reading = "Head-First Design Patterns (Ch 3); or Gang of Four (Ch 13)"
assignment = "Sprint 2"

[[weeks.days]]
date = "Feb 3"
topic = "Sprint Evaluation; Peer Review / Team Topics; Factory; Singleton"
reading = "Head-First Design Patterns (Ch 4/5); or Gang of Four (Ch 2/3)"
assignment = "Sprint 2"

[[weeks]]
num = 5

[[weeks.days]]
date = "Feb 6"
topic = "Amdahl's Law; Code Smells; Sprint 2 Object Diagrams"
assignment = "Sprint 2"

[[weeks.days]]
date = "Feb 8"
topic = "Strategy Pattern; Null Pattern; Anti-Patterns; Refactoring; Technical Debt"
reading = "Head-First Design Patterns; Gang of Four"
assignment = "Sprint 2"

[[weeks.days]]
date = "Feb 10"
topic = "Sprint Deliverables; In-Class Code Review Meetings; Levels; File I/O"
assignment = "Sprint 2 Functionality Check-In due on Feb 12 at 11:59pm"

[[weeks]]
num = 6

[[weeks.days]]
date = "Feb 13"
topic = "Code Reviews (Group Schedule TBD)"
assignment = "Sprint 2"

[[weeks.days]]
date = "Feb 15"
topic = "Code Reviews (Group Schedule TBD)"
assignment = "Sprint 2"

[[weeks.days]]
date = "Feb 17"
topic = "Code Reviews (Group Schedule TBD)"
assignment = "Sprint 2 Due on Feb 19 at 11:59pm"

[[weeks]]
num = 7

[[weeks.days]]
date = "Feb 20"
topic = "CATME Peer Reviews; Sprint 3 Q&A; Collision Detection; Movement"
assignment = "Sprint 3 Start; CATME Peer Reviews for Sprint 2"

[[weeks.days]]
date = "Feb 22"
topic = "Collision Detection; Movement; Collision Response; Software Organization for Game Physics"
assignment = "Sprint 3"

[[weeks.days]]
date = "Feb 24"
topic = "Cameras; Camera Controls; Quality Assurance (QA); Unit Testing"
assignment = "Sprint 3"

[[weeks]]
num = 8

[[weeks.days]]
date = "Feb 27"
topic = "OSU Graphics Courses; Mid-Semester Feedback"
assignment = "Sprint 3"

[[weeks.days]]
date = "Mar 1"
topic = "Playtesting; Planning For End Product"
assignment = "Sprint 3"

[[weeks.days]]
date = "Mar 3"
topic = "Code Reviews and Group Meeting Time"
assignment = "Sprint 3 Functionality Check-In due on Mar 5 at 11:59pm"

[[weeks]]
num = 9

[[weeks.days]]
date = "Mar 6"
topic = "Code Reviews (Group Schedule TBD)"
assignment = "Sprint 3"

[[weeks.days]]
date = "Mar 8"
topic = "Code Reviews (Group Schedule TBD)"
assignment = "Sprint 3"

[[weeks.days]]
date = "Mar 10"
topic = "Code Reviews (Group Schedule TBD)"
assignment = "Sprint 3 due on Mar 19 at 11:59pm"

[[weeks]]
num = 10

[[weeks.days]]
date = "Mar 13"
topic = "No Class"

[[weeks.days]]
date = "Mar 15"
topic = "No Class"

[[weeks.days]]
date = "Mar 17"
topic = "No Class"

[[weeks]]
num = 11

[[weeks.days]]
date = "Mar 20"
topic = "Sprint 4 Q&A; Audio; Heads-Up Display"
assignment = "Sprint 4 Start; CATME Peer Reviews for Sprint 3"

[[weeks.days]]
date = "Mar 22"
topic = "Entity Component Systems"
assignment = "Sprint 4"

[[weeks.days]]
date = "Mar 24"
topic = "Flyweight Pattern; Object Pools; Build Pattern; Memento Pattern"
reading = "Head-First Design Patterns; Gang of Four"
assignment = "Sprint 4"

[[weeks]]
num = 12

[[weeks.days]]
date = "Mar 27"
topic = "Under The Hood of SpriteBatch"
assignment = "Sprint 4"

[[weeks.days]]
date = "Mar 29"
topic = "Primer on Real-Time 3D Graphics"
assignment = "Sprint 4"

[[weeks.days]]
date = "Mar 31"
topic = "Looking Towards Sprint 5"
assignment = "Sprint 4 Functionality Check-In due on Apr 2 at 11:59pm"

[[weeks]]
num = 13

[[weeks.days]]
date = "Apr 3"
topic = "Code Reviews (Group Schedule TBD)"
assignment = "Sprint 4"

[[weeks.days]]
date = "Apr 5"
topic = "Code Reviews (Group Schedule TBD)"
assignment = "Sprint 4"

[[weeks.days]]
date = "Apr 7"
topic = "Code Reviews (Group Schedule TBD)"
assignment = "Sprint 4 due on Apr 9 at 11:59pm"

[[weeks]]
num = 14

[[weeks.days]]
date = "Apr 10"
topic = "Sprint 5 Q&A; Code Reviews and Group Meeting Time"
assignment = "Sprint 5 Start; CATME Peer Reviews for Sprint 4"

[[weeks.days]]
date = "Apr 12"
topic = "TBD; Code Reviews and Group Meeting Time"
assignment = "Sprint 5"

[[weeks.days]]
date = "Apr 14"
topic = "TBD; Code Reviews and Group Meeting Time"
assignment = "Sprint 5"

[[weeks]]
num = 15

[[weeks.days]]
date = "Apr 17"
topic = "Code Reviews and Group Meeting Time"
assignment = "Sprint 5"

[[weeks.days]]
date = "Apr 19"
topic = "Code Reviews and Group Meeting Time"
assignment = "Sprint 5"

[[weeks.days]]
date = "Apr 21"
topic = "Code Reviews and Group Meeting Time"
assignment = "Sprint 5"

[[weeks]]
num = 16

[[weeks.days]]
date = "Apr 24"
topic = "Early Project Presentations; Course Wrap-Up"
assignment = "Sprint 5 Due at 11:59pm; CATME Peer Reviews for Sprint 5"
